name = "UPEncodingModels"
uuid = "55a56ed5-3bc8-4039-874f-1a9e7a603a30"
version = "1.0.0-DEV"
authors = ["Ben Lankow <ben.lankow@gmail.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LinearAlgebra = "1.12.0"
Plots = "1.41.6"
Random = "1.11.0"
SparseArrays = "1.12.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
